import { createTypes } from 'reduxsauce';

export default createTypes(`
  PUSH_NEW_ROUTE
  REPLACE_ROUTE
  REPLACE_OR_PUSH_ROUTE
  POP_ROUTE
  POP_TO_ROUTE
  LOAD_TASKS_REQUEST
  LOAD_TASKS_ERROR
  LOAD_TASKS_SUCCESS
  SET_HOME_TAB
  SET_MYAPP_TAB
  POP_AGENT_MODAL
  SET_LOCATION
  SET_DISTANCE
  SET_USER
  SET_PRE_ROUTE
  SET_SPINNER_VISIBLE

  PRODUCT_FILTER_VALUE
  PRODUCT_GET
  PRODUCT_GET_SEARCH
  PRODUCT_GET_RENDER
  PRODUCT_SET_OFFER
  PRODUCT_SET_FAVOURITE

  LOGIN_ATTEMPT
  FBLOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  SIGNUP_ATTEMPT
  SIGNUP_SUCCESS
  SIGNUP_FAILED

  FILTER_ATTEMPT

  SET_CHANNELS_STATE
  SET_UNREAD_STATE
  SET_MESSAGE
  SET_RESPONSE_MSG

  SET_ONESIGNAL_INFO

  SHOW_SHARE_VIEW
  SET_BADGE
  SET_LOCATION_PERMISSION
`);
